# NumPy Basics

This notebook demonstrates fundamental NumPy operations used for numerical computing in Python.

## Topics Covered
- Array creation
- Array attributes
- Indexing and slicing
- Mathematical operations
- Reshaping

## File
- `numpy_basics.ipynb`

## Notes
The focus is on clarity and foundational understanding of NumPy.

### Numpy: Numerical Python.
* Used for numerical computation, powerful python library for handeling mathematical & numerical operations.
* Two main data structures: Array & Matrix.
* Work with large, multidimensional array & perform complex mathematical operations between them.

### Numpy Array:
Stores a sequence of elements of the same data type. Arrays can be can be one dimensional (sequence) & two dimensional (row & column) or multidimensional.
Faster as compared to python list.

In [1]:
pip install numpy #whenever u need to install a library , this one is to install numpy

In [2]:
import numpy as np # to use numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

### Creating a 1D Array

In [5]:
n0 = [1, 2, 3, 4 ,5]
n1 = np.array(n0)

In [6]:
print(n1)

[1 2 3 4 5]


### Creating an array from Scratch

In [7]:
# np.zeros() & np.ones() to create arrays filled with 0s & 1s
array1 = np.zeros(10)
array2 = np.ones(15)
print(array1)
print(array2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
# np.arange() functions in Numpy like python range() to create sequence
# start: starting number | end: Ending number | step: Difference between numbers(default is 1)
print(np.arange(12))
array3 = np.arange(3, 20, 2)
print(array3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  5  7  9 11 13 15 17 19]


In [9]:
#np.linspace() function: Creates and array with evenly spaced numbers with a range
# start: starting value of range | end: ending value of range | num: numbers of values to create
np.linspace(1,10,2)

array([ 1., 10.])

In [10]:
np.linspace(1,10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
# elements between 10 & 100 with stepsize 4
arange1 = np.arange(1, 100, 4)
print (arange1)
# Generate 4 elements betn 1 & 100
linspace1 = np.linspace(1, 100, 4)
print (linspace1)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
[  1.  34.  67. 100.]


In [12]:
# Numpy can also create arrays with random numbers using random modules using the syntax: np.random.randint()
# Random numbers between 1 and 51
random_number = np.random.randint(1,51)
print(random_number)

18


In [13]:
#generate 10 numbers between 1 and 51
print (np.random.randint(1,51,10))

[ 3 42 32 50  7 43 41  1 43 26]


In [14]:
# array of length 7 with random integer values range from 1 upto 80
rand_array = np.random.randint(1,81,7)
print ('7 random integer values ranging from 1 to 80:', rand_array)

7 random integer values ranging from 1 to 80: [ 3 23 28 74 23 74 71]


In [15]:
# we can used np.random.rand() to create an array of random numbers between 0 and 1
# generate an array of 6 random numbers between 0 and 1
array1 = np.random.rand(4)

In [16]:
# You can create an empty array using np.empty()
print(np.empty(4))

[  1.  34.  67. 100.]


## Array Indexing

In [17]:
list1 = [1, 7, 5, 9, 11]


In [18]:
# Numpy array: Index starts from 0
array1 = np.array([3, 4, 5, 6, 7])


In [19]:
# access each elements
print(array1[0])

3


In [20]:
for i in array1:
  print(i)

3
4
5
6
7


In [21]:
#positive indexing
try:
  print(array1[5])
except Exception as e:
  print('This error is', e)

This error is index 5 is out of bounds for axis 0 with size 5


In [22]:
# negative indexing
print(array1[-2])

6


In [23]:
# Boolean indexing: lets the selection of values in array based on conditions
# select only the odd numbers in the array
numbers = np.array([1, 2 ,3 ,4 ,5 ,6 ,7 , 8, 9, 10])
odd_numbers = numbers [numbers%2!=0]
print(odd_numbers)

[1 3 5 7 9]


In [24]:
# select only the even numbers in the array
even_numbers = numbers[numbers%2==0]
print(even_numbers)

[ 2  4  6  8 10]


In [25]:
# Fancy indexing: allows you to select multiple elements from an array using arrays or lists of specific elements
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
# select elements at index 1, 2, 6, 7
elements = numbers[[1,2,6,7]]
print(elements)

[2 3 7 8]


In [27]:
# Array Slicing: Numpy allows you to select parts in an array just like slicing in python
# Access the first 4 elements of an array
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
sliced_numbers = numbers[:4]
print(sliced_numbers)

[1 2 3 4]


### Array Attributes
Simple properties of Numpy array that tell us basic details about the array.
**Attributes and their meaning:**
- ndim: Number of dimensions
- shape: size of the array in each dimension
- dtype: type of data stored in array
- itemsize: size of each element in bytes
- nbytes: total memory usd by the array


In [29]:
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
print('Number of dimensions:', numbers.ndim)
print('Shape:', numbers.shape)
print('Data Types:', numbers.dtype)
print('Itemsize:', numbers.itemsize)
print('Memory size:', numbers.nbytes)

Number of dimensions: 1
Shape: (10,)
Data Types: int64
Itemsize: 8
Memory size: 80


### Mathematical Operations

In [31]:
first = np.array([1, 9, 12, 16])
second = np.array([2, 3, 6, 8])

In [32]:
sum = np.add(first, second)
print (sum)

[ 3 12 18 24]


In [33]:
divide = np.divide(first, second)
print (divide)

[0.5 3.  2.  2. ]


In [34]:
multiply = np.multiply(first, second)
print(multiply)

[  2  27  72 128]


In [35]:
power = np.power(first, second)
print(power)

[         1        729    2985984 4294967296]


### Comparision Operator

In [36]:
# <: use of less()
print(np.less(first, second))

[ True False False False]


In [37]:
# <=: use of less_equal()
print(np.less_equal(first, second))

[ True False False False]


In [38]:
# >: use of greater()
print(np.greater(first, second))

[False  True  True  True]


In [39]:
# >=: use of greater_equal()
print(np.greater_equal(first, second))

[False  True  True  True]


In [40]:
# ==: use of equal()
print(np.equal(first, second))

[False False False False]


In [41]:
# !=: use of not_equal()
print(np.equal(first, second))

[False False False False]


### Logical Operator

In [42]:
x1 = np.array([1, 1, 2, 2, 6, 5, 3])
x2 = np.array([1 ,2 ,3 ,4 ,5 ,6 ,8])

In [43]:
# Logical AND
print(np.logical_and(x1, x2))

[ True  True  True  True  True  True  True]


In [44]:
# Logical OR
print(np.logical_or(x1, x2))

[ True  True  True  True  True  True  True]


In [45]:

# Logical NOT
print(np.logical_not(x1, x2))

[0 0 0 0 0 0 0]


### Statistical Functions
1. Maximum Value: np.max()
2. Minimum Value: np.min()
3. Measures of Central Tendency
- Mean: np.mean()
- Median: np.median()
4. Measure of dispersion
- Standard Deviation: np.std()
- Range: np.max() - np.max()
- Variance: np.var()
- Percentile: np.percentile(data, [x, y])

In [46]:
# 2D array
array1 = np.array([[1,2,3],[4,5,6]])
print(array1.ndim)

2


In [47]:
# 3D array
array2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array2.ndim)

3


In [48]:
# Create a 2D array with 3 rows and 4 columns
list1 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
print(list1)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [49]:
np1 = np.array(list1)
print(np1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
# Create an empty 2D array with 2 rows and 3 columns
np2 = np.empty((3,2))
print(np2)

[[5.03616394e-315 0.00000000e+000]
 [1.97319090e+093 1.63041663e-322]
 [6.92224037e-310 6.92224037e-310]]


In [51]:
# Create 3 x 3 array all filled with the value 9
numpy_array = np.full((3,2),9)
print(numpy_array)

[[9 9]
 [9 9]
 [9 9]]


In [52]:
#Reshape: Gives a data without changing array
print(np.reshape(numpy_array,(2,3)))

[[9 9 9]
 [9 9 9]]


In [53]:
# Matrix: 2d array arranged in rows and column
matrix1 = np.matrix([[1,2],[3,4]])
matrix2 = np.matrix([[2,2],[3,3]])

In [54]:
# Operators in matrix : *: Multiply || **: power
print('Multiplication of matrix:', matrix1*matrix2)
print('Power in matrix', matrix1**2)

Multiplication of matrix: [[ 8  8]
 [18 18]]
Power in matrix [[ 7 10]
 [15 22]]


In [55]:
matrix1@matrix2

matrix([[ 8,  8],
        [18, 18]])

In [56]:
# Transpose matrix: Rows to column and column to rows
print(np.transpose(matrix1))

[[1 3]
 [2 4]]


In [60]:
# Filter: actions that are determined by conditions (true or false)
array1 = np.array([[1, 2, 3, -1, -2, -3], [-5, -6, -7, 5, 6, 7]])
filtered_arr =(array1 > 0)
print(filtered_arr)

[[ True  True  True False False False]
 [False False False  True  True  True]]


In [62]:
#where()
print(np.where(array1<0, 0, array1))

[[1 2 3 0 0 0]
 [0 0 0 5 6 7]]


In [63]:
#any()
print(np.any(array1 < 3))

True


In [64]:
#all()
print(np.all(array1>2))

False


In [65]:
#stack()
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])
print(np.stack([array1, array2, array3]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
# vertical Stack
print(np.vstack([array1, array2, array3]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
# Horizontal Stack
print(np.hstack([array1, array2, array3]))

[1 2 3 4 5 6 7 8 9]


In [68]:
print(np.sum(array1))

6


In [71]:
# Masked Array: Ordinary numpy array where some values are masked or ignored
from numpy.ma import MaskedArray
m = array1 > 5
print(MaskedArray(array1, m))

[1 2 3]
